### PR TITLE
allow 1.x version range

### LINKED ISSUE #5: Unable to install with Laravel 5.6
Because of https://github.com/laravel/framework/blob/5.6/composer.json#L26

### PR DESCRIPTION
**Pull request by pquerner**
fixes #5

### CODE REVIEW

**Comment by repat** [comment]
Carbon v1.0.0 would be also allowed but doesn't have `parse()`, see https://github.com/briannesbitt/Carbon/blob/d59535c3175d1188baea460bd7772d41ea227b56/Carbon/Carbon.php

Function needed from Carbon:
```php
if (Carbon::parse($this->config["valid_until"])->gt(Carbon::now())) {
			return true;
		}
// ...
$this->config["valid_until"] = Carbon::now()->addSeconds($response["expiresIn"])->toDateTimeString();
```

Alternatively, you could also write this in plain PHP and remove Carbon dependency (preferred). I don't want to update this to Carbon 1.25.X and possibly break dependencies for other people because they can't install a higher Carbon than what's in the `composer.json` now.

**Comment by pquerner** [comment]
OK so you want alteast 1.22.1 but not greater than the current released version. (Which is 1.27.0 as of 2 days ago)
I guess ```~1.22.1``` would do the trick aswell. Also this is interesting.. https://github.com/briannesbitt/Carbon/issues/1250

I try to come up with a better solution tonight and report it asap.

**Comment by pquerner** [comment]
I have added a commit which uses minimal 1.22.1 and allows anything up until semantic 2.0.0 is released. They shouldnt break existing functions in 1.x, only add features or fix bugs.

**Comment by repat** [comment]
Thanks!

**Pull request merged**
